### ISSUE TITLE
Component Sublists

### ISSUE THREAD

**Issue by samcdavid** [spartansystems/atomic_cms#2]
As admin editing a page, I want to be able to select multiple values for a single component option.

**Comment by sonofabear** [comment]
+1 on this. Currently creating multiple components that this would be required on. Like image galleries, team members, etc. Idea for a good solution might be to save some kind of object containing all of the entries into the field (JSON?) @Mrjaco12 @squaresurf I can go over my thoughts on how the interface could work on this if you want.

**Comment by samcdavid** [comment]
@Mrjaco12, is this issue done?

**Comment by Mrjaco12** [comment]
I guess it is. Would you look at that.
